services:
  postgres:
    image: postgres:16
    restart: unless-stopped
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: college_schedule
    ports:
      - "5432:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data
      - ./main/migrations/0001_init.up.sql:/docker-entrypoint-initdb.d/0001_init.sql
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 5s
      timeout: 5s
      retries: 5

  api:
    build:
      context: /main
    restart: unless-stopped
    environment:
      DATABASE_URL: postgres://postgres:postgres@postgres:5432/college_schedule?sslmode=disable
      ALLOWED_ORIGINS: http://localhost:5500, http://127.0.0.1:5500, https://budka-iteam.github.io/inter_map/
      PORT: 8080
      JWT_SECRET: "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJzdWIiOiJ1c2VyMSIsImV4cCI6MTc5MDE2MTE0OX0.zQznmkRnTskraBuG_t6CLh498RBlpdZDwg3Dsh_wLDo"
      ADMIN_USERNAME: "stray228"
      ADMIN_PASSWORD: "1488"
    ports:
      - "8080:8080"
    depends_on:
      postgres:
        condition: service_healthy
  
  parser:
    build:
      context: ../parser
      dockerfile: Dockerfile
    environment:
      COLLEGE_SCHEDULE_DB_DSN: postgres://postgres:postgres@postgres:5432/college_schedule?sslmode=disable
      PARSE_INTERVAL_HOURS: "6"
    depends_on:
      postgres:
        condition: service_healthy

volumes:
  pgdata: